'''
处理Excel电子表格
Python的openpyxl模块让我们可以在Python程序中读取和修改Excel电子表格
当然实际工作中，我们可能会用LibreOffice Calc和OpenOffice Calc来处理Excel的电子表格文件
这就意味着openpyxl模块也能处理来自这些软件生成的电子表格。
关于openpyxl的使用手册和使用文档可以查看它的官方文档。
https://openpyxl.readthedocs.io/en/stable/#

处理Word文档
利用python-docx模块，Pytho 可以创建和修改Word文档
当然这里的Word文档不仅仅是指通过微软的Office软件创建的扩展名为docx的文档
LibreOffice Writer和OpenOffice Writer都是免费的字处理软件。

处理PDF文档
PDF是Portable Document Format的缩写，使用.pdf作为文件扩展名。
接下来我们就研究一下如何通过Python实现从PDF读取文本内容和从已有的文档生成新的PDF文件。
'''